uPortal-Project/NotificationPortlet

notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationState.java
notification-portlet-webapp/pom.xml
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/action/read/ReadAction.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/AbstractNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/INotificationDao.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaAction.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaAddressee.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaAttribute.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaEntry.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaEvent.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaNotificationDao.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaRecipient.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/rest/RestfulJsonNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/util/UsernameFinder.java
notification-portlet-webapp/src/main/resources/META-INF/persistence.xml
notification-portlet-webapp/src/main/resources/datasource.properties
notification-portlet-webapp/src/main/resources/ehcache.xml
notification-portlet-webapp/src/main/resources/messages.properties
notification-portlet-webapp/src/main/webapp/WEB-INF/context/applicationContext.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/persistenceContext.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/emergency-alert.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/notification-icon.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/notification.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/web.xml
pom.xml

https://issues.jasig.org/browse/NOTIFPLT-49
* https://wiki.jasig.org/display/PLT/JpaNotificationService+-+Push-Model+Notifications

NOTIFPLT-49:  Implement a JpaNotificationService

---

.gitignore
notification-portlet-webapp/pom.xml
notification-portlet-webapp/src/main/resources/datasource.properties
pom.xml

Note that import and export were not added, just the dbinit support

Added dbinit support for the JpaPlusREST_feature code

---

.gitignore
notification-portlet-webapp/src/main/resources/META-INF/persistence.xml

Added hibernate dialect to the persistence.xml file - needed for POSTGRES

persistence.xml needs hibernate dialect

---

notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaNotificationDao.java

POSTGRES will not work properly with those set in the Transactional annotation

NOJIRA - removed propagation from Transactional annotations

---

.gitignore
notification-portlet-webapp/pom.xml
notification-portlet-webapp/src/main/resources/datasource.properties
pom.xml

support added for dbinit (maven target) to drop and create the notifications tables via JPA

Added dbinit support

---

notification-portlet-webapp/src/main/webapp/less/accordion.less
notification-portlet-webapp/src/main/webapp/scripts/jquery.notifications.js

https://issues.jasig.org/browse/NOTIFPLT-62
Added the due date to the notifications item detail screen, along with wrapping it in conditional formatting depending on if it's past due.

NOTIFPLT-62: Added due date to notifications item detail

---

notification-portlet-api/pom.xml
notification-portlet-api/src/main/java/org/jasig/portlet/notice/JsonAttributesDeserializer.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/JsonAttributesSerializer.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/JsonDateDeserializer.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/JsonDateSerializer.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/JsonNotificationActionDeserializer.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationAction.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationAttribute.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationCategory.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationEntry.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationError.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationResponse.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/rest/ActionDTO.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/rest/AddresseeDTO.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/rest/AttributeDTO.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/rest/EntryDTO.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/rest/EventDTO.java
notification-portlet-api/src/main/java/org/jasig/portlet/notice/rest/RecipientDTO.java
notification-portlet-api/src/test/java/org.jasig.portlet.notice/JsonDeserializationTest.java
notification-portlet-api/src/test/java/org.jasig.portlet.notice/JsonSerializationTest.java
notification-portlet-webapp/pom.xml
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/classloader/ClassLoaderResourceNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/IJpaNotificationRESTService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/rest/RestfulJsonNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/ssp/SSPToken.java
notification-portlet-webapp/src/main/webapp/WEB-INF/views.xml
pom.xml

https://issues.jasig.org/browse/NOTIFPLT-70
This change was work as a result of debuggin NOTIFPLT-69.

NOTIFPLT-70: Upgrade Jackson Json library to 2.0

---

notification-portlet-webapp/src/main/webapp/WEB-INF/jsp/accordion.jsp

https://issues.jasig.org/browse/NOTIFPLT-71

NOTIFPLT-71: Remove extraneous end div in accordion.jsp.

---

.gitignore
notification-portlet-webapp/src/main/webapp/WEB-INF/jsp/accordion.jsp

Re-opened https://issues.jasig.org/browse/NOTIFPLT-71. Wrong end div tag removed. Corrected.

NOJIRA: Ignore IntelliJ IDE files

---

.travis.yml
pom.xml

[NOTIFPLT-82](https://issues.jasig.org/browse/NOTIFPLT-82)
Setup Travis CI build to include Checkstyle configured to use the Google Code Style.

NOTIFPLT-82: Setup Travis CI and Checkstyle with Google Code Style

---

README.md
appveyor.yml

https://issues.jasig.org/browse/NOTIFPLT-83
Build Output: https://ci.appveyor.com/project/ChristianMurphy/notificationportlet-1k8ep/build/1.0.1

NOTIFPLT-83: Add AppVeyor as Windows Continuous Integration

---

notification-portlet-api/pom.xml
notification-portlet-webapp/pom.xml
pom.xml

https://issues.jasig.org/browse/NOTIFPLT-88
Particularly on smart phones, long messages could easily become a usability issue.

NOTIFPLT-88:  

---

notification-portlet-api/pom.xml
notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationResponse.java
notification-portlet-webapp/pom.xml
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/controller/emergency/EmergencyAlertAdminController.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/controller/emergency/EmergencyAlertController.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/controller/rest/JPANotificationRESTController.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/CacheNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/classloader/ClassLoaderResourceNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/classloader/DemoNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/event/PortletEventNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/FilteringNotificationServiceDecorator.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jdbc/AbstractJdbcNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jdbc/AnyRowResourceContentJdbcNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaNotificationRESTService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/rest/RestfulJsonNotificationService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/util/JpaServices.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/util/PortletXmlRoleService.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/util/UsernameFinder.java
notification-portlet-webapp/src/main/resources/ehcache.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/applicationContext.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/emergency-alert-admin.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/emergency-alert.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/notification-icon.xml
notification-portlet-webapp/src/main/webapp/WEB-INF/context/portlet/notification.xml
pom.xml

https://issues.jasig.org/browse/NOTIFPLT-91
This enhancement provides flexible abstract (and a bit of concrete) support for querying JDBC data sources for notifications.

NOTIFPLT-91:  Provide an AbstractJdbcNotificationService and appropriate subcless(es) to support SQL-based data sources

---

notification-portlet-webapp/build.gradle
notification-portlet-webapp/package-lock.json
notification-portlet-webapp/package.json

Fix CSS/LESS/JS compilation & minification in existing pre-portlets for for version 4

---

notification-portlet-webcomponents/notification-component-icon/package.json
notification-portlet-webcomponents/notification-component-icon/src/NotificationIcon.js
notification-portlet-webcomponents/yarn.lock

Ensure read is appropriately parsed, fix usage with Apereo Open ID Connect helper.

Issue 73 Part 2

---

notification-portlet-webcomponents/notification-component-icon/src/NotificationIcon.js
notification-portlet-webcomponents/notification-component-icon/src/i18n.js

refactor: tree shake react i18n and open id connect

---

notification-portlet-webcomponents/notification-component-icon/package.json
notification-portlet-webcomponents/notification-component-icon/src/NotificationIcon.js
notification-portlet-webcomponents/yarn.lock

particularly open id connect helper to see impact on bundle size
See https://github.com/uPortal-contrib/uPortal-web-components/pull/21

chore: update node modules

---

README.md
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/BodyTextNotificationFilter.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/FilteringNotificationServiceDecorator.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/TextNotificationFilter.java
notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/TitleTextNotificationFilter.java
notification-portlet-webapp/src/main/webapp/WEB-INF/portlet.xml

Resolves #102.
This may require additional work to support web components.

enh(#102): Add notice filter by title / body regex matching.

---

notification-portlet-webcomponents/notification-banner/package-lock.json
notification-portlet-webcomponents/notification-banner/package.json
notification-portlet-webcomponents/notification-banner/src/components/NotificationBanner.vue
notification-portlet-webcomponents/notification-component-icon/package-lock.json
notification-portlet-webcomponents/notification-modal/package-lock.json
notification-portlet-webcomponents/notification-modal/package.json
notification-portlet-webcomponents/notification-modal/src/components/NotificationModal.vue

arrow functions and class will break IE

fix: include babel patches to notification banner wc wrapper

---

notification-portlet-webcomponents/notification-banner/babel.config.js
notification-portlet-webcomponents/notification-banner/package-lock.json
notification-portlet-webcomponents/notification-banner/package.json
notification-portlet-webcomponents/notification-component-icon/package-lock.json
notification-portlet-webcomponents/notification-modal/babel.config.js
notification-portlet-webcomponents/notification-modal/package-lock.json
notification-portlet-webcomponents/notification-modal/package.json

The `@babel/preset-env` at least works on Chrome.

fix:  revert @vue/babel-preset-app -> @babel/preset-env

---

notification-portlet-webcomponents/notification-modal/src/components/NotificationModal.vue
notification-portlet-webcomponents/notification-modal/src/components/ieButton.vue
notification-portlet-webcomponents/notification-modal/src/components/ieModal.vue

simplified code and removes an unneeded ref.
Adds custom components for ie and edge with fewer features to avoid infinite recursion.

fix: ie support

---

notification-portlet-webcomponents/notification-component-icon/src/NotificationIcon.js

Setting the unread count to 0 instead of an empty string to fix issue…

Setting the unread count to 0

---

notification-portlet-webcomponents/notification-component-icon/src/NotificationIcon.js

Added styling to fix alignment and icon size

CSS Tweak for sizing

---

notification-portlet-webcomponents/notification-icon/src/components/NotificationIcon.vue
notification-portlet-webcomponents/notification-icon/src/components/ieDropdown.vue
notification-portlet-webcomponents/notification-icon/src/components/ieDropdownHeader.vue
notification-portlet-webcomponents/notification-icon/src/components/ieDropdownItem.vue

Fixes issue with it not rendering in Edge

fix: issue with the latest version not rendering in IE

---

notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaNotificationDao.java

This fixes an incompatibility with Oracle CLOBs.
Resolves #150.

fix(150): remove distinct keyword

---

notification-portlet-webcomponents/notification-banner/package-lock.json
notification-portlet-webcomponents/notification-icon/README.md
notification-portlet-webcomponents/notification-icon/package-lock.json
notification-portlet-webcomponents/notification-icon/src/components/NotificationIcon.vue
notification-portlet-webcomponents/notification-modal/package-lock.json

feat: Add option to count all notifications

---

notification-portlet-webcomponents/notification-icon/src/components/NotificationItem.vue

fix(icon-component): updated item to render the notification's title

---

notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/rest/UserAttributeParameterEvaluator.java

This PR updates UserAttributeParameterEvaluator to support multi-valued claims

feat: updated UserAttributeParameterEvaluator to support multi-valued claims

---

notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/jpa/JpaEntry.java

fix: correct fetch type from LAZY to EAGER

---

notification-portlet-webapp/src/main/webapp/WEB-INF/jsp/accordion.jsp
notification-portlet-webapp/src/main/webapp/scripts/jquery.notifications.js

Use browser language/locale for date format in notification portlet

fix: update JS date formatter to use browser locale

---

.github/workflows/CI.yml

Added Java 11 to github build (while keeping Java 8)

UPSE-294: added Java 11 to github build
